version: '3'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
